name: Verification du PokeDex

on:
  pull_request:
  push:
    branches:
      - dev

jobs:
  mon-premier-job-de-test:
    runs-on: ubuntu-latest

    steps:
      - name: Afficher un message
        run: echo "La pipeline GitHub Actions fonctionne !"